In [1]:
%pip install faraway

Note: you may need to restart the kernel to use updated packages.


### Step 0

In [2]:
# CodeGrade step0
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



### Step 1

*  [Data](https://rdrr.io/cran/faraway/man/pima.html)
*  [Faraway](https://pypi.org/project/faraway/)

In [3]:
# CodeGrade step0

# Load the Dataset from faraway
from faraway.datasets import pima

# Load the dataset
data = pima.load()

# Convert 'diabetes' column to int type to represent classes 0 and 1; remove the handful of 2s (unkown) in the data
data['diabetes'] = data['diabetes'].astype(int)
data = data[data['diabetes'] != 2]

In [5]:
# Display the first few rows and info
data.head()

,pregnant,glucose,diastolic,triceps,insulin,bmi,diabetes,age,test
0,6,148,72,35,0,33.6,0,50,1
1,1,85,66,29,0,26.6,0,31,0
2,8,183,64,0,0,23.3,0,32,1
3,1,89,66,23,94,28.1,0,21,0
5,5,116,74,0,0,25.6,0,30,0


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 764 entries, 0 to 767
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pregnant   764 non-null    int64  
 1   glucose    764 non-null    int64  
 2   diastolic  764 non-null    int64  
 3   triceps    764 non-null    int64  
 4   insulin    764 non-null    int64  
 5   bmi        764 non-null    float64
 6   diabetes   764 non-null    int32  
 7   age        764 non-null    int64  
 8   test       764 non-null    int64  
dtypes: float64(1), int32(1), int64(7)
memory usage: 56.7 KB


In [7]:
# CodeGrade step1

# Shape
data.shape

(764, 9)

### Step 2

In [8]:
# CodeGrade step2

# Clean the Data
# Check for missing values

data.isnull().sum()

pregnant     0
glucose      0
diastolic    0
triceps      0
insulin      0
bmi          0
diabetes     0
age          0
test         0
dtype: int64

### Step 3


In [9]:
# CodeGrade step3

# Encode the Target Variable
# The target variable is already in binary format (0 = No, 1 = Yes), no encoding required.
data['diabetes'].unique()

array([0, 1])

### Step 4

In [10]:
# CodeGrade step4

#  Define Features and Scale the Data
# Define features (X) and target (y)
X = data.drop('diabetes', axis=1)
y = data['diabetes']

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, 
    test_size=0.2, 
    random_state=42,
    stratify=y
)


### Step 5

In [12]:
# CodeGrade step5

# Build and Train the Logistic Regression Model
# Instantiate the logistic regression model, call this 'model'
model = LogisticRegression()

# Train the model on the training set
model.fit(X_train, y_train)

# Make Predictions
# Predict probabilities, 'y_pred_proba' and classes, 'y_pred', give the first 10
y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities for class 1
y_pred = model.predict(X_test)  # Predicted classes
y_pred[:10], y_pred_proba[:10]


(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0.07739162, 0.08966185, 0.03842467, 0.04291019, 0.03245101,
        0.03990606, 0.03231352, 0.03634736, 0.03909383, 0.03436831]))